export enum CHECK_POINT_TYPE {
  NOUVEAU_POTEAU = 'NOUVEAU_POTEAU',
  POTEAU_FRANCE_TELECOM = 'POTEAU_FRANCE_TELECOM',
  POTEAU_BETON_N10 = 'POTEAU_BETON_N10',
  POTEAU = 'POTEAU',
  ARMOIRE = 'ARMOIRE',
  CHAMBRE_FRANCE_TELECOM = 'CHAMBRE_FRANCE_TELECOM',
  FACADE = 'FACADE',
  SOUTE = 'SOUTE'
}
